### ISSUE TITLE
Develop Airship 2.0 Wharf Deployment Guide

### ISSUE THREAD

**Issue by michaelfix** [airshipit/docs#20]
As an operator, I need an Airship 2.0 Deployment Engineer (DE) Guide, so that I can have a Method of Procedures (MoP) list for configuring, deploying, and validating, via automated pipelines an Airship 2 deployment into a 6-node (3 controller, 3 worker) environment (aka Wharf env), including SIP/ViNO integration and sub-cluster deployment.

The DE Guide is a complement to the [Airship 2 Docs Deployment Guide](https://docs.airshipit.org/airship2/baremetal.html); however, intended for internal consumption.

Environment Under Test (EUT):  mtn66c (w/ mtn65c successful)

**Comment by MichelleE-11** [comment]
WIP Downstream PS: 
https://gerrit.mtn5.cci.att.com/c/nc-release/+/93887

Manifest pending merge:
https://gerrit.mtn5.cci.att.com/c/nc-regions-labs/+/93584

**Comment by michaelfix** [comment]
Initial DG for A2 deployment (without sub-clusters complete and Merged documentation as of 6/9):
WIP Downstream PS:
https://gerrit.mtn5.cci.att.com/c/nc-release/+/93887

Manifest pending merge:
https://gerrit.mtn5.cci.att.com/c/nc-regions-labs/+/93584

Next steps:  Enhance DG to include SIP/ViNO & sub-cluster deployment steps.

**Comment by eak13** [comment]
Closing given Wharf has completed & no plans to do anything further with it.
