### ISSUE TITLE
Expand Airship 2.0 AIAP Setup and Use Guide to include additional platforms

### ISSUE THREAD

**Issue by michaelfix** [airshipit/docs#21]
As an operator, I need an expanded Airship In A Pod (AIAP) Guide, which extends the existing [AIAP Document](https://docs.airshipit.org/airship2/airship-in-a-pod.html) for install, deployment, and validation across non-native Linux platforms.

To include, but not limited to:

- Prerequisites (env needed)
- Deploying a K8s cluster (inclusive of minikube, docker)
- Deploying AIAP
- Usage (interacting with the POD

The AIAP Guide will be an extension of the existing documentation for 1-to-n platforms (e.g. Windows+VirtualBox, Google Cloud Platform (GCP) VMs, etc).

**Comment by pgoyal01** [comment]
Please assign Issue #21 to me (Github id: pgoyal01). Thanks

**Comment by eak13** [comment]
@pgoyal01 all yours!

**Comment by eak13** [comment]
Closing as this has been resolved.
