### ISSUE TITLE
Develop Airship 2.0 Frequently Asked Questions (FAQs)

### ISSUE THREAD

**Issue by michaelfix** [airshipit/docs#22]
As an operator, I need an Airship 2.0 Frequently Asked Questions (FAQs) guide, so that I can have a centralized location of user, developer, operator, questions to provide common direction and assistance for onboarding, development, supported versions, etc.

The FAQs Guide will reside in a new Airship 2 Reference section on the existing [Airship 2 Docs](https://docs.airshipit.org/) website.

**Comment by ss8171** [comment]
I will be working this one

**Comment by eak13** [comment]
Closing as we have the hackmd page for tracking any FAQs
