### ISSUE TITLE
Develop Airship 2.0 SIP/VINO Reference Material

### ISSUE THREAD

**Issue by michaelfix** [airshipit/docs#24]
As an operator, I need Airship 2.0 Reference Material for SIP and VINO, so that I can have support documentation on how this new capability works, how it integrates with the Airship 2 platform, how to test and maintain the sub-clusters which are created using SIP/VINO capabilities. 

The SIP/VINO Reference Material will reside in the Airship Project Documentation on the existing [Airship 2 Docs](https://docs.airshipit.org/) website.

**Comment by ldurway** [comment]
Please assign to me.

**Comment by lb4368** [comment]
Cancelling this since not needed at this time
