### ISSUE TITLE
Update Airship 2.0 Deployment Guide for v2.1

### ISSUE THREAD

**Issue by lb4368** [airshipit/docs#36]
In support of v2.1 GA, update the Site Deployment Guides for specifying deployment of phase plans as opposed to deploying individual phases one-by-one.

**Comment by jgu17** [comment]
Labelled size M considering the effort of creating baremetal phase plan and test it out on the stl3 env in addition to doc update

**Comment by jgu17** [comment]
https://review.opendev.org/c/airship/docs/+/795424
https://review.opendev.org/c/airship/docs/+/795191

**Comment by jgu17** [comment]
Done
