### ISSUE TITLE
SPIKE: Identify out of date Airship One documentation & broken links in https://docs.airshipit.org

### ISSUE THREAD

**Issue by eak13** [airshipit/docs#38]
**Enhancement description**
With a move to Airship 2, we need to go through & determine which Airship 1 pages are out of date & where there are broken links on https://docs.airshipit.org. Once we have a list of pages/links identified, we can review & determine the path forward which may include either updating or retiring. 

**Proposed change**
- Develop a gate script that acts as a URL checker (reviews each documentation page, curls all urls & reports out on broken ones)
- Identify any broken links ​
- Identify Airship 1 pages that are out of date 
- Report back for review

**Comment by DannyMassa** [comment]
Assign to me and I'll draw up a report.

Thanks

**Comment by DannyMassa** [comment]
size s

**Comment by DannyMassa** [comment]
Here's the report:

    doc\source\airship2\airship-in-a-pod.rst
        FAIL: https://github.com/airshipit/airshipctl/blob/master/tools/airship-in-a-pod/airship-in-a-pod.yaml
        FAIL: https://raw.githubusercontent.com/airshipit/airshipctl/master/tools/airship-in-a-pod/airship-in-a-pod.yaml
    doc\source\airship2\baremetal.rst
        FAIL: https://jenkins.nc.opensource.att.com/job/Deployment/job/stl3-type-core
        FAIL: https://jenkins.nc.opensource.att.com/job/development/job/Airshipctl
    doc\source\airship2\site-deployment.rst
        FAIL: https://docs.airshipit.org/airshipctl/cli/airshipctl_config.html
    doc\source\develop\api-conventions.rst
        FAIL: https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#response-status-kind


SUCCESS: 138     FAILED: 6     SKIPPED: 0

**Comment by eak13** [comment]
Closing this issue as the report has been generated. #43 has been created to go fix the broken links.
