### ISSUE TITLE
[airshipctl] airshipctl SYNTAX issue

### ISSUE THREAD

**Issue by pgoyal01** [airshipit/docs#4]
The typical airshipctl command syntax is of the form

`airshipctl [TYPE] [command] [sub-command] [flags]`

where TYPE = {baremetal, cluster, config, plan, ...}, and the commands, sub-commands and flags, except for help, are specific to the TYPE.

However, `airshipctl completion SHELL` doesn't follow the syntax. This is not a documentation issue as it requires a change in the code.

**Comment by jgu17** [comment]
this issue should be filed in https://github.com/airshipit/airshipctl/issues, if the cmd syntax needs to be changed.

**Comment by pgoyal01** [comment]
@jgu17 Agree. But this served as a test of my being able to create an issue here.

**Comment by pgoyal01** [comment]
Opened [airshipctl syntax issue](https://github.com/airshipit/airshipctl/issues/519) as per @jgu17 suggestion.

Closing this issue here.
