### ISSUE TITLE
Fix out of date Airship One documentation & broken links in https://docs.airshipit.org

### ISSUE THREAD

**Issue by eak13** [airshipit/docs#43]
**Description**
Leveraging the report created in issue #38, either fix or remove the broken links in https://docs.airshipit.org.

**Tasks**
1. For each broken link, determine if there is an updated source & change the URL to point to the correct webpage.
2. If new source cannot be found, then remove the link reference.
3. Validate the Airship documentation pages render correctly with the updated URLs & the URLs take users to the correct webpages.

**Comment by lb4368** [comment]
PS: https://review.opendev.org/c/airship/docs/+/805042

**Comment by gtsteffaniak** [comment]
assign to me

**Comment by DannyMassa** [comment]
airshipctl\CONTRIBUTING.md
    FAIL: https://doc.airshipit.org/airshipctl/developers.html
airshipctl\docs\source\phases.rst
    FAIL: https://godoc.org/opendev.org/airship/airshipctl/pkg/clusterctl/client#ClusterctlExecutor
    FAIL: https://10.23.25.102:6443
    FAIL: https://10.23.25.101:6443
    FAIL: https://godoc.org/opendev.org/airship/airshipctl/pkg/clusterctl/client#ClusterctlExecutor
airshipctl\docs\source\plugins.md
airshipctl\docs\source\providers\cluster_api_azure.md
    FAIL: https://review.opendev.org/airship/airshipctl
airshipctl\docs\source\providers\cluster_api_docker.md
    FAIL: https://review.opendev.org/airship/airshipctl
    FAIL: https://review.opendev.org/airship/airshipctl
airshipctl\docs\source\providers\cluster_api_gcp.md
    FAIL: https://review.opendev.org/airship/airshipctl
airshipctl\docs\source\providers\cluster_api_openstack.md
    FAIL: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/docs/env.rc
    FAIL: http://cdimage.ubuntu.com/releases/18.04/release/ubuntu-18.04.5-server-amd64.iso
    FAIL: http://10.0.4.4/identity
airshipctl\docs\source\secrets-guidelines.md
    FAIL: https://github.com/GoogleContainerTools/kpt-functions-catalog/tree/master/examples/contrib/sops
airshipctl\docs\source\virtual_redfish_bmc.md
    FAIL: https://github.com/dell-esg/tool-pkgs/blob/master/Redfish_tools.zip
    FAIL: http://192.168.122.10:8000/redfish/v1/Systems
    FAIL: http://192.168.122.10:8000/redfish/v1/Systems/8e5b2dc4-0c1d-4509-af2f-7a4a8f2121a8
airshipctl\manifests\function\cni\tigera-operator\README.rst
    FAIL: https://github.com/airshipit/airshipctl/tree/master/manifests/function/tigera-operator/v1.15.0/custom-resources.yaml
docs\doc\source\airship2\baremetal.rst
    FAIL: https://jenkins.nc.opensource.att.com/job/Deployment/job/stl3-type-core
    FAIL: https://jenkins.nc.opensource.att.com/job/development/job/Airshipctl
docs\doc\source\airship2\site-deployment.rst
    FAIL: https://docs.airshipit.org/airshipctl/cli/airshipctl_config.html
docs\doc\source\develop\api-conventions.rst
    FAIL: https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#response-status-kind
docs\doc\source\develop\code-conventions.rst
    FAIL: https://opendev.org/airship/images/src/branch/master/image-builder/Dockerfile.ubuntu_focal


SUCCESS: 284     FAILED: 22     SKIPPED: 0

**Comment by lb4368** [comment]
Closing this issue as https://review.opendev.org/c/airship/docs/+/805042 has merged.

New issues created to address newly identified broken links above:

- https://github.com/airshipit/airshipctl/issues/644
- #44
