### ISSUE TITLE
Fix Broken Links in Docs

### ISSUE THREAD

**Issue by lb4368** [airshipit/docs#44]
**Describe the bug**
The docs broken link finder has identified the following broken links in airship documentation. Review and update documentation as needed to resolve.

docs\doc\source\airship2\baremetal.rst
FAIL: https://jenkins.nc.opensource.att.com/job/Deployment/job/stl3-type-core
FAIL: https://jenkins.nc.opensource.att.com/job/development/job/Airshipctl
docs\doc\source\airship2\site-deployment.rst
FAIL: https://docs.airshipit.org/airshipctl/cli/airshipctl_config.html
docs\doc\source\develop\api-conventions.rst
FAIL: https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#response-status-kind
docs\doc\source\develop\code-conventions.rst
FAIL: https://opendev.org/airship/images/src/branch/master/image-builder/Dockerfile.ubuntu_focal

**Comment by joshuaherrera** [comment]
I believe Graham took care of this issue with this PS which was merged:
https://review.opendev.org/c/airship/docs/+/805042

**Comment by lb4368** [comment]
@joshuaherrera   Good catch.  The tool must have been run before that merge.  I will cancel this.  Thanks!
