### ISSUE TITLE
Enhance Broken Link Linter Job to canvass all Airship readme/repos

### ISSUE THREAD

**Issue by michaelfix** [airshipit/docs#45]
**Enhancement description**
Enhance the existing Docs Repo Linter Job to scan artifacts for broken, or out of date links, in Airship2 readme PSs/repos, including https://docs.airshipit.org. Once we have a list of pages/links identified, review & determine the path forward which may include either updating or retiring.

**Proposed change**

- Enhance the broken-link linter gate script that acts as a URL checker (reviews each documentation page, curls all urls & reports out on broken ones) to scan readmes within Airship2 repos
- Identify any broken links ​
- Identify pages that are out of date
- Report back for review
- Retire, or Resolve broken links and obsolete artifacts

**Comment by DannyMassa** [comment]
Relevant PS's:
- https://review.opendev.org/c/airship/airshipctl/+/800528
- https://review.opendev.org/c/airship/treasuremap/+/813658
- https://review.opendev.org/c/airship/docs/+/813545

**Comment by DannyMassa** [comment]
The patchsets listed above have been merged, we should be able to close this issue.

**Comment by michaelfix** [comment]
Related PSs merged.  Closed Issue.
