### ISSUE TITLE
V2.0 GA Documentation - A2 Release Notes

### ISSUE THREAD

**Issue by michaelfix** [airshipit/docs#7]
V2 release notes

Airship 2 release details to define Overview of AS2, 2.0 Core Features, and Change Log (of GitHub Issues and Enhancements).

To be published under "Release Notes" on https://docs.airshipit.org/.

Author: Lindsey Durway (ld178u)

**Comment by michaelfix** [comment]
PS WIP - https://review.opendev.org/c/airship/docs/+/784486

**Comment by ldurway** [comment]
Assign to me

**Comment by lb4368** [comment]
@ld178u Done.  Thanks!

**Comment by eak13** [comment]
closing per code merge
