### ISSUE TITLE
V2.0 GA Documentation - A2 AIAP

### ISSUE THREAD

**Issue by michaelfix** [airshipit/docs#8]
Airship In A Pod (AIAP) documentation.

In support of V2.0 GA, the AIAP documentation defines for the user the following user steps/guide to define and use AIAP:

- What is AIAP
- Prerequisites (env needed)
- Deploying a K8s cluster (inclusive of minikube, docker)
- Deploying AIAP
- Usage (interacting with the POD

To be published under "Try Airship 2, then Airship in a Pod (AIAP)" on https://docs.airshipit.org/.

Author:  Pankaj Goyal (pg683k)

**Comment by michaelfix** [comment]
PS WIP - https://review.opendev.org/c/airship/docs/+/784509

**Comment by pgoyal01** [comment]
Please assign to me

**Comment by eak13** [comment]
@pgoyal01 done! Thanks

**Comment by eak13** [comment]
Closing per code merge
